name: Flutter Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    # See https://github.com/subosito/flutter-action 
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.13.7'
    - run: flutter pub get
    - run: flutter analyze
    - run: flutter test
